services:
  postgres-service:
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql-service/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data: