FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:20

ENV DATABASE_URL="postgres://postgres:admin@postgres-service:5432"

USER node
WORKDIR /workspaces/prisma-foreign-key-update
WORKDIR /workspaces/diffraction
